# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c107edecd394577ef9188510dd32eb246e1284b2ea0357fa453b4b5e0658bc4e190289754bb557b61f53a0e2037217958fa1d77ca3e49a67fee4818f78b8becf

test:
  secret_key_base: d6619ea995900d367b61298e342469128cec539101cbb19d55e5e6cfbc8c6b449c5ccd2420c9cb313215f6c568c64b8046b3e83d7425ada077c6fe6c8f0c36b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
